version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "iodeslykos"
    commit-message:
      prefix: "chore(actions)"
